### ISSUE TITLE
Script runs forever when creating group of 2 or 3 shapes/charts

### ISSUE THREAD

**Issue by badger707** [OfficeDev/office-scripts-docs-reference#147] opened 2021-11-06 00:10 UTC
## Article URL
https://docs.microsoft.com/en-us/javascript/api/office-scripts/excelscript/excelscript.worksheet?view=office-scripts#addGroup_values_

## Issue
When attempting to make a new group from several pie charts or text boxes, script runs but never finishes and must be stopped manually (no errors, just runs forever).
Scenario for 3 pie charts and 1 text box.
`
function main(workbook: ExcelScript.Workbook)
{
let charts_sheet_name = "PieChartSheet";
let chart_sheet = workbook.getWorksheet(charts_sheet_name);
let shape_1 = chart_sheet.getShape("Chart 1");
let shape_2 = chart_sheet.getShape("Chart 2");
let shape_3 = chart_sheet.getShape("Chart 3");
let shape_4 = chart_sheet.getShape("Chart 4");
let text_box_1 = chart_sheet.getShape("TextBox 1");

//trying to create new group - this is where this hangs forever
let my_shapes_group = chart_sheet .addGroup([shape_1, shape_2, shape_3, shape_4, text_box_1]);
//just testing final output in b64
let new_group_image = my_shapes_group .getImageAsBase64(ExcelScript.PictureFormat.png);
console.log(new_group_image);
}
`
Expected result - new group of charts/shapes created. (then I'd return this b64 image to power automate for further processing -- no issues with that part, its just addGroup is causing issues).

What I'm missing? Any pointers/advise?

**Comment by AlexJerabek** [comment] 2021-11-08 19:47
Hi @badger707,

Thank you for the question, hopefully I can provide some insight.

One thing I can say is that [Charts](https://docs.microsoft.com/en-us/javascript/api/office-scripts/excelscript/excelscript.chart?view=office-scripts) and [Shapes](https://docs.microsoft.com/en-us/javascript/api/office-scripts/excelscript/excelscript.shape?view=office-scripts) are two different things in the Office Scripts object model. I don't believe you can group Charts like that. However, even when I was testing with shapes I hit the same unresponsiveness issue. I also hit what might be a separate issue while trying to make a repro script.

```
function main(workbook: ExcelScript.Workbook) {
	let selectedSheet = workbook.getActiveWorksheet();
	// Insert shape _5_Point_Star_1
	let _5_Point_Star_1 = selectedSheet.addGeometricShape(ExcelScript.GeometricShapeType.star5);
	// Insert shape can_2
	let can_2 = selectedSheet.addGeometricShape(ExcelScript.GeometricShapeType.can);

	let group = selectedSheet.addGroup([_5_Point_Star_1, can_2]);
	//just testing final output in b64
	let new_group_image = group.getImageAsBase64(ExcelScript.PictureFormat.png);
	console.log(new_group_image);
}
```

But, using the Shape IDs instead of the Shape objects worked fine (`	let group = selectedSheet.addGroup([_5_Point_Star_1.getId(), can_2.getId()]);`. As a short-term workaround, can you please try switching to an array of IDs instead of Shape objects? I'm not sure that'll help with the Chart versus Shape issue, but it's worth a try.

@jeremy-msft, can you please help me triage the possible underlying issues in the Shape APIs?

**Comment by badger707** [comment] 2021-11-08 21:11
Hi @AlexJerabek -- thanks for guidance, indeed proposed workaround with IDs in array works just fine for both - charts and shapes.

- Related question - base64 encoded images are 96 DPI as per API docs - is there a plan to build/provide higher DPI? Its just sometimes 96 DPI is not enough and images/charts are not that sharp/crisp...

**Comment by AlexJerabek** [comment] 2021-11-08 21:51
Thanks @badger707. We have passed your information about the unresponsiveness issue on to the feature crew. They will investigate and I'll keep you updated.

As for the DPI request, I would recommend going to the [M365 Developer Platform Tech Community space](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) and making that feature request. We use Tech Community to help prioritize customer requests. The more upvotes your idea receives, the more likely it is the team will prioritize and develop that feature.

**Comment by AlexJerabek** [comment] 2021-11-08 23:50
@badger707 You can also submit feature requests through the Office Scripts Code Editor. In the Code Editor task pane's **More options (…)** menu, select the **Send feedback** button to share your request for higher exported image DPI.

![image](https://user-images.githubusercontent.com/38896772/140836304-f052008b-07f6-48a1-9a14-368ea15a089c.png)

**Comment by AlexJerabek** [comment] 2021-11-19 18:25
Hi @badger707,

Circling back to confirm that we've identified the root cause for the group creation bug. We're working on a fix. I'll update the thread when we have an ETA for release.

**Comment by badger707** [comment] 2021-11-19 18:29
Hi @AlexJerabek 

Thanks for update, good news, looking forward for release.

**Comment by AlexJerabek** [comment] 2021-11-29 20:13
Hi @badger707,

We have completed a fix and released it to production. You should be good to go. I'm going to close the issue, but please let us know if you encounter other problems or have questions.

Thanks!

**Closed by AlexJerabek** 2021-11-29 20:13 UTC
Labels: Status: under investigation, Type: product bug
