### ISSUE TITLE
setHyperlink properties do not accept interpolated strings.

### ISSUE THREAD

**Issue by umaxy** [OfficeDev/office-scripts-docs-reference#286] opened 2023-09-13 19:41 UTC
## Article URL
(https://learn.microsoft.com/en-us/javascript/api/office-scripts/excelscript/excelscript.range?view=office-scripts#excelscript-excelscript-range-sethyperlink-member(1))

## Issue
The example shows the use of interpolated strings. Documentation shows interpolated strings to follow:

$"<text> {<interpolated-expression> [,<field-width>] [:<format-string>] } <text> ..."

 The version in the example and documentation does not work.

**Comment by AlexJerabek** [comment] 2023-09-13 20:35
Hi @umaxy,

I just tested the sample for `Range. setHyperlink` and it works as intended. Could you please share the Code Editor error you're getting?

**Comment by umaxy** [comment] 2023-09-13 21:43
Your right it does work. I just noticed a back quote was used instead of a single quotation. I've read documentation on single and double quotes but is the back quote interpreted the same way?

**Comment by umaxy** [comment] 2023-09-13 21:51
The method only works with back quotes. You cannot use the following [https://learn.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/strings/interpolated-strings](url). Is there any explanation for that behavior?

**Comment by AlexJerabek** [comment] 2023-09-13 21:59
That link is to the Visual Basic language reference. Office Scripts are written in TypeScript (which is a superset of JavaScript). The use of a backtick is for [Template Literal Types](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html). Single or double quote strings do not allow for variables and would have to be assembled through string concatenation. Functionally, the following two lines are the same:
```
let text = `Setting hyperlink of ${cell.getAddress()} to the ${linkedSheetName} sheet's A1 cell`;
```
```
let text = "Setting hyperlink of " + cell.getAddress() + " to the " + linkedSheetName + " sheet's A1 cell";
```

Personally, I find the first version more readable and less likely to miss a space or something.

**Comment by AlexJerabek** [comment] 2023-09-14 15:37
Closing this issue, since we've confirmed the samples are fine. Happy to keep chatting about TypeScript in the comments.

**Closed by AlexJerabek** 2023-09-14 15:37 UTC
Labels: Needs: attention :wave:, Type: doc bug

**Comment by umaxy** [comment] 2023-09-14 15:45
Thanks Alex for pointing this all out.
